### PR TITLE
Update Atomix Go SDK to v0.13.2

### PR DESCRIPTION
**Pull request by kuujo**

### CODE REVIEW

**Comment by kuujo** [comment]
@SeanCondon can you see Jenkins? When I run the tests locally the linter seems to hang indefinitely. Not sure if that's just a different issue with my machine though.

**Comment by SeanCondon** [comment]
retest this pelase

**Comment by SeanCondon** [comment]
ran it again - same problem - will send you full console log in PM

**Comment by ray-milkey** [comment]
retest this please

**Review by ray-milkey — APPROVED** [review]

**Pull request merged**
